version: '3.4'

services:
  mlsamsungoct:
    image: ml-samsung-oct-2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    # command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]